name: Run Tests

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup V
        uses: vlang/setup-v@v1.4

      - name: Run tests
        run: v test .
